import { readFileSync, writeFileSync, cpSync, mkdirSync, rmSync } from 'node:fs';
import { factoryFloor } from './floor.mjs';
const report = JSON.parse(readFileSync('site/data/experiments.json', 'utf8'));
if (report.runs.length !== 3 || report.runs.some(run => !run.passed)) throw new Error('All three real experiments must discriminate before publication');
const escape = value => String(value).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
rmSync('dist', { recursive: true, force: true });
cpSync('site', 'dist', { recursive: true });
let html = readFileSync('site/index.html', 'utf8');
html = html.replace('<!--FLOOR-->', factoryFloor());
html = html.replace('<!--EXPERIMENT_BUTTONS-->', report.runs.map((run,index) => '<button class="experiment-choice" data-experiment="'+index+'" aria-pressed="'+(index===0)+'"><span>EXP / '+String(index+1).padStart(3,'0')+'</span>'+escape(run.title)+'</button>').join(''));
html = html.replace('<!--FIRST_TRANSCRIPT-->', escape(report.runs[0].transcript));
html = html.replace('<!--RUN_DATE-->', 'RECORDED '+escape(report.completedAt));
html = html.replace('<!--RUN_ORIGIN-->', 'Recording environment: '+escape(report.environment)+'.');
html = html.replace('<strong id="clean-result">—</strong>', '<strong id="clean-result">GREEN / '+report.runs[0].cleanScore+'</strong>');
html = html.replace('<strong id="drift-result">—</strong>', '<strong id="drift-result">RED / '+report.runs[0].driftScore+'</strong>');
html = html.replace('</body>', '<script type="application/json" id="experiment-data">'+JSON.stringify(report).replaceAll('<','\\u003c')+'</script>\n</body>');
if (/<!--[A-Z_]+-->/.test(html)) throw new Error('Unresolved content marker');
writeFileSync('dist/index.html', html);
mkdirSync('dist/data', { recursive: true });
writeFileSync('dist/data/site.json', JSON.stringify({ name:'Odin R&D', version:'0.1.2', issued:'2026-09-07', builtAt:new Date().toISOString(), source:'https://github.com/odin-labs-ai/odin-rnd', revision:report.revision, experimentRun:report.workflowRun, drawing:'Conceptual software-factory assembly; not a map of deployed infrastructure.' }, null, 2)+'\n');
writeFileSync('dist/.nojekyll','');
console.log('Built static GitHub Pages site with three recorded experiments.');
