export const escape = value => String(value).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#39;');
export const format = value => typeof value==='string'?value:JSON.stringify(value,null,2);
export const transcript = (r,o) => o.commandIds.map(id=>{const c=r.commands.find(c=>c.id===id);return `${c.id}: ${c.executable} ${c.args.join(' ')}\ncwd: ${c.cwd}\n${c.status}; exit ${c.exitCode}; ${c.durationMs} ms\nstdout:\n${c.stdout}\nstderr:\n${c.stderr}`;}).join('\n\n');
export function renderWitness(html,r){
 const first=r.observations.find(o=>o.role==='negative-control'&&o.verdict==='rejected')||r.observations[0];
 const fields={
 WITNESS_META:`<p class="witness-record-label">Recorded fixture run · ${escape(r.environment)} · ${escape(r.completedAt)}</p><p>Run ${escape(r.runId)} · base source revision <code>${escape(r.sourceRevision)}</code></p><p>${escape(r.workingTree.description)}</p>${r.workflowRun?`<p><a href="${escape(r.workflowRun)}/attempts/${r.workflowAttempt}">GitHub Actions recording · attempt ${r.workflowAttempt}</a></p>`:''}<p>${escape(r.scope)}</p><details><summary>Runtime and experiment boundaries</summary><pre>${escape(format(r.runtime))}</pre><ul>${r.limitations.map(x=>`<li>${escape(x)}</li>`).join('')}</ul><p><a href="../../data/witnesses/${r.project}.json">Raw execution record</a> · <a href="../../data/witnesses/manifest.json">Source hashes and recording manifest</a></p></details>`,
 WITNESS_METRICS:`<dl class="witness-metrics">${r.metrics.map(m=>`<div><dt>${escape(m.id)}</dt><dd><strong>${m.numerator} / ${m.denominator}</strong> ${escape(m.unit)}<p>${escape(m.definition)}</p></dd></div>`).join('')}</dl>`,
 WITNESS_BENCH:`<label for="witness-choice">Recorded case</label><select id="witness-choice" disabled>${r.observations.map(o=>`<option value="${escape(o.id)}"${o===first?' selected':''}>${escape(o.id)} · ${escape(o.verdict)}</option>`).join('')}</select><h3 id="witness-case">${escape(first.caseId)}</h3><p id="witness-verdict">${escape(first.verdict)}</p><p id="witness-reason">${escape(first.reason)}</p><div class="witness-compare"><div><h4>Expected</h4><pre id="witness-expected">${escape(format(first.expected))}</pre></div><div><h4>Actual</h4><pre id="witness-actual">${escape(format(first.actual))}</pre></div></div><details><summary>Actual command transcript</summary><pre id="witness-transcript">${escape(transcript(r,first))}</pre></details>`,
 WITNESS_TABLE:r.observations.map(o=>`<details id="observation-${escape(o.id)}"><summary>${escape(o.id)} · ${escape(o.verdict)}</summary><p>${escape(o.reason)}</p><h4>Expected</h4><pre>${escape(format(o.expected))}</pre><h4>Actual</h4><pre>${escape(format(o.actual))}</pre><h4>Execution receipt</h4><pre>${escape(transcript(r,o))}</pre></details>`).join('')};
 for(const [marker,content] of Object.entries(fields)){const token=`<!--${marker}-->`;if(html.split(token).length!==2)throw new Error(`Missing or duplicate ${marker} on ${r.project}`);html=html.replace(token,content);}
 return html.replace('</body>',`<script type="application/json" id="witness-data">${JSON.stringify(r).replaceAll('<','\\u003c')}</script>\n</body>`);
}
